### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by vfonic** [Shopify/theme-check-action#13]
I'm running theme-check-action for the first time on a repo that belongs to a brand new GitHub organization.

This is the GH action yml:

```yml
name: Theme Check
on: [push]
jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          # flags: '--fail-level style'
          token: ${{ github.token }}
          base: master
```

This is the error that I get:
 
```
Successfully installed ast-2.4.2
Successfully installed parser-3.1.2.0
Successfully installed liquid-5.3.0
Successfully installed theme-check-1.10.2
4 gems installed
$ theme-check --version
1.10.2
$ theme-check --fail-level style -o json .
Checking . ...
$ git fetch origin master
From https://github.com/<redacted>
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
$ git diff --name-only --diff-filter=ACMRTUB origin/master
Creating GitHub check...
HttpError: Resource not accessible by integration
    at /var/task/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (internal/process/task_queues.js:[9](https://github.com/<redacted>/runs/6652177544?check_suite_focus=true#step:4:10)5:5)
    at async Job.doExecute (/var/task/node_modules/bottleneck/light.js:405:[18](https://github.com/<redacted>/runs/6652177544?check_suite_focus=true#step:4:19))
Error: Resource not accessible by integration
```

Any ideas what could've gone wrong?

**Comment by vfonic** [comment]
Note that when I comment-out `token` and `base`, the check runs successfully and reports:

> 431 files inspected, 3788 offenses detected, 2879 offenses auto-correctable

Could it be that `${{ github.token }}` is not available because the repo is under the org?

**Comment by vfonic** [comment]
I forked the repo to my private account and now I'm not getting _any_ errors, but the theme-check action fails. It shows 0 errors and 0 warnings and a failure. How can I debug this?

<details>
<summary>Theme Check Report (I've exluded *zipifypages.liquid via config file)</summary>

![Screen Shot 2022-05-31 at 09 51 57](https://user-images.githubusercontent.com/67437/171083483-ba29f9de-b0fd-4de7-a2c5-1629fe62fc90.jpg)

</details>

<details>
<summary>Theme Check (I've added &lt;redacted&gt; to anything that could be potentially sensitive information)</summary>

![Screen Shot 2022-05-31 at 09 53 21](https://user-images.githubusercontent.com/67437/171083495-ff2d0a83-1182-4558-9b10-f050c6d12e99.jpg)

</details>

**Comment by charlespwd** [comment]
The issue with no errors would be that no files were diffed in your PRs. 

> `base` (optional) When `token` is set, **only the files that contain a diff with this ref** (branch, tag or commit) will have GitHub check annotations.

Could it be that your PR only had the GitHub action in it?

**Comment by vfonic** [comment]
Yes, that's very much possible. :) Hmmm, would you say that in that case the build should pass? Perhaps a warning would suffice?

This build failing prevents any changes to non-theme files such as:
- README
- prettierrc
- any-other-rc
- any other changes to JS/CSS build system
- etc.

I believe the build should pass. What do you think?

**Comment by vfonic** [comment]
I made sure there's at least one liquid file in the changelist, but I'm still getting the same error. I mean, I'm not getting any error and the build fails. :)

Everything same as before:
Theme Check Report
0 error(s), 0 warning(s) found

How would you recommend debugging this?

Here's the list of changes:
![Screen Shot 2022-06-03 at 07 50 26](https://user-images.githubusercontent.com/67437/171763801-6d2c08f3-bd75-40de-b5e2-3f76c8742106.jpg)

There are two more files changed:
- removed unrelated GH Action file that's making the build fail on this fork
- the GH Action for running the theme-check-action as written in the first comment here

**Comment by mkromann** [comment]
I fixed this issue by giving the token more permission. Details here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions

**Comment by andershagbard** [comment]
I am getting the same error on a self-hosted runner.

```
Creating GitHub check...
HttpError: Resource not accessible by integration
    at /runner/_work/_actions/shopify/theme-check-action/v2/dist/index.js:1:147122
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (/runner/_work/_actions/shopify/theme-check-action/v2/dist/index.js:1:155877)
Error: Resource not accessible by integration
```

```
permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  theme-check:
    name: Theme Check
    runs-on: self-hosted
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: './src'
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
```

`secrets.GITHUB_TOKEN` is working perfectly in other workflows.
