### ISSUE TITLE
The "path" argument must be of type string. Received null

### ISSUE THREAD

**Issue by chrish-d** [Shopify/theme-check-action#15]
I'm getting this error when I try to run this action:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (internal/errors.js:3[22](https://github.com/<redacted-account>/<redacted-repo>/runs/6879185751?check_suite_focus=true#step:4:23):7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at /index.js:72:20
    at Array.map (<anonymous>)
    at /index.js:70:10
    at async /index.js:67:20
```

Here's my config:

```yaml
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: "."
          token: ${{ github.token }}
          base: v2
```
