### ISSUE TITLE
Can't run v2  with `--dev-preview`

### ISSUE THREAD

**Issue by AlejandroE** [Shopify/theme-check-action#32]
👋🏼 Hi, I'm trying to upgrade to `shopify/theme-check-action@v2` but the action fails with:

` ›   Error: Nonexistent flag: --dev-preview`

I've seen this flag defaults to true since https://github.com/Shopify/theme-check-action/pull/30 but the public version of the shopify cli doesn't run when called with this flag. 

This is the job I'm running: 
```
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      ...
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          theme_root: './dist'
          flags: '--fail-level error --config .theme-check-dist.yml'
```

and this is the output where it adds the flag I didn't specify in the config: 

```
Run shopify/theme-check-action@v2
  with:
    theme_root: ./dist
    flags: --fail-level error --config .theme-check-dist.yml

x64/bin/npm install --no-package-lock --no-save @shopify/cli @shopify/theme

added 1634 packages, and audited 188 packages in 30s

297 packages are looking for funding
  run `npm fund` for details

15 vulnerabilities (9 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
/runner/_work/theme/node_modules/.bin/shopify theme check --dev-preview --fail-level error --config .theme-check-dist.yml --path ./dist
╭─ error─────────────────╮
│                                                                              │
│  Nonexistent flag: --dev-preview                      │
│  See more help with --help                                │
│                                                                              │
╰────────────────────╯

 ›   Error: Nonexistent flag: --dev-preview
 ›   See more help with --help
```

The flag also fails locally with shopify v3.55.4

<img width="666" alt="Screenshot 2024-02-09 at 16 41 41" src="https://github.com/Shopify/theme-check-action/assets/5765722/4d5f1d84-aa3d-46c2-b6d9-0688b5f2cb0c">

Please let me know if there's something I missed or if it's a bug on your side. Thanks in advance :)
