### ISSUE TITLE
Theme Check v2 issues with `theme_root` and `root` dir

### ISSUE THREAD

**Issue by knjshimi** [Shopify/theme-check-action#36]
It seems that when the `root` is specified in `.theme-check.yml` and in the action, it's not finding the theme folder.

## Example 1: `root` + `root` (Fails)

`.theme-check.yml`
```yml
root: src

MatchingTranslations:
  enabled: false
```

`action.yml`
```yml
- name: 💧 Theme check
  uses: shopify/theme-check-action@v2
    with:
      theme_root: './src'
```

The above combination will result in a bunch of `MatchingTranslations` errors.

## Example 2: `root` + `--config` (Fails)

`.theme-check.yml`
```yml
root: src

MatchingTranslations:
  enabled: false
```

`action.yml`
```yml
- name: 💧 Theme check
  uses: shopify/theme-check-action@v2
    with:
      theme_root: './src'
      flags: '--config .theme-check.yml'
```

The above combination will result in `0 files inspected with no offenses`. I believe theme check thinks the theme root is `./src/src`.

## Example 3: `root` + custom config (Works)

If I create a new `.theme-check-ci.yml` and remove the `root`:
```yml
MatchingTranslations:
  enabled: false
```

`action.yml`
```yml
- name: 💧 Theme check
  uses: shopify/theme-check-action@v2
    with:
      theme_root: './src'
      flags: '--config .theme-check-ci.yml'
```

If will correctly use the configuration.

**Comment by charlespwd** [comment]
I think you're missing a use case, `root` in .theme-check.yml and _not_ in the GitHub action:

```yml
root: src

MatchingTranslations:
  enabled: false
```
`action.yml`
```yml
- name: 💧 Theme check
  uses: shopify/theme-check-action@v2
```

I _believe_ that should work. Right now the `root` arg gets passed to the command as the `--path` argument. So by specifying _both_, you're actually looking for src/src (which is why it doesn't work)

Also, it might not find your --config when you change the root.

I've tried running `shopify theme check --path .` in a folder that looks like this and everything worked out fine:

```
.
├── .theme-check.yml
└── dist
    ├── assets
    ├── blocks
    ├── config
    ├── layout
    ├── locales
    ├── sections
    ├── snippets
    └── templates
```
