### ISSUE TITLE
Theme check fails even when it passes

### ISSUE THREAD

**Issue by wrainbird** [Shopify/theme-check-action#44]
Hello!

I've set this up and all appeared to be going well, I've been testing it with deliberate theme check errors on a PR.

However, now I have fixed the errors, the theme check still fails. I thought this may be similar to #28  - but I do have changed liquid files in the PR.

Comparing the results to a successful action in Dawn, I can't see what is causing this. However we do have our sections inside a `_sections` folder (we run our own build tool for shared schemas which gets compiled into a `sections` folder before we run `shopify theme package`), which theme check does pick up, but maybe that could be causing the error code? 

My workflow:
```
name: Push
on: [push]

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
       # Add configuration to .theme-check.yml
      - name: Update .theme-check.yml
        run: |
          echo "" >> .theme-check.yml
          echo "RequiredDirectories:" >> .theme-check.yml
          echo "  enabled: false" >> .theme-check.yml

      # Theme Check
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}
          base: development
  ```
  
Screenshots:
<img width="1175" alt="image" src="https://github.com/Shopify/theme-check-action/assets/1315304/89fed519-3350-4f87-b578-992615458d7f">

<img width="756" alt="image" src="https://github.com/Shopify/theme-check-action/assets/1315304/bfbb5042-47fe-41b4-876a-2d60246ebb18">

Similar successful action on a Dawn commit:

<img width="1192" alt="image" src="https://github.com/Shopify/theme-check-action/assets/1315304/cc86ab53-e345-4624-9724-a523e0ecb7b5">

<img width="725" alt="image" src="https://github.com/Shopify/theme-check-action/assets/1315304/f9e96f79-c2f7-4bd5-a99c-dfabfc0b7171">
