### ISSUE TITLE
Theme Check failing in Github

### ISSUE THREAD

**Issue by marcusYKT** [Shopify/theme-check-action#52]
Around a month a go my theme check on Github started failing. I haven't changed anything in my _theme-check.yml_ file.

```yaml
# .github/workflows/theme-check.yml
name: Theme Check
on: [push]
jobs:
  theme-check:
    permissions: write-all
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: master
```
---
Screenshot of the failed theme check on Github. Doesn't provide any useful errors.

<img src="https://github.com/user-attachments/assets/42d85bf1-9d48-4036-88f7-65a74e95a255" width="400">

---

Also when I run theme check on my local it logs no errors.

<img src="https://github.com/user-attachments/assets/2860d963-985d-4ffb-bd3f-cc98015f6062" width="400">

**Comment by aswamy** [comment]
> Doesn't provide any useful errors.

What does "Theme Check Report" in the GitHub Action say?

> Also when I run theme check on my local it logs no errors.

Hmm that one is quite suspicious. Only happens when you run `shopify theme check` outside a shopify theme.

**Comment by marcusYKT** [comment]
> What does "Theme Check Report" in the GitHub Action say?

0 error(s), 0 warning(s) found. Which I find is really weird.
<img src="https://github.com/user-attachments/assets/c050f459-3d62-4b49-aba5-522eef2afda3" width="400">


> Hmm that one is quite suspicious. Only happens when you run `shopify theme check` outside a shopify theme.
Inside Github actions and on my local enviroment.

Do you want a copy of the raw logs? I downloaded once to comb through it but nothing really stuck out to me.

---
Thanks for you reply!

**Comment by aswamy** [comment]
Yes @marcusYKT, any logs are useful. Also, could i see the `theme-check.yml` file. I want to be able to recreate this error on my theme repo.

**Comment by marcusYKT** [comment]
Sorry for the delay. Here is my theme-check.yml file as well.
```yaml
# .github/workflows/theme-check.yml
name: Theme Check
on: [push]
jobs:
  theme-check:
    permissions: write-all
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          theme_root: '.' # optional, could be './dist'
          token: ${{ github.token }}
          base: master
```

**Comment by marcusYKT** [comment]
Here is my `.theme-check.yml` file. Unfortunately Theme Check still fails on Github. No errors or warnings either.
Ah, I thought I needed `base` in my workflow. Let me try removing it.

```yaml
extends: theme-check:recommended
ignore:
  - node_modules/**
# AssetPreload:
#   enabled: true
#   severity: 1
# BlockIdUsage:
#   enabled: true
#   severity: 1
# CaptureOnContentForBlock:
#   enabled: true
#   severity: 0
# CdnPreconnect:
#   enabled: true
#   severity: 0
# ContentForHeaderModification:
#   enabled: true
#   severity: 0
# DeprecateBgsizes:
#   enabled: true
#   severity: 1
# DeprecateLazysizes:
#   enabled: true
#   severity: 1
# DeprecatedFilter:
#   enabled: true
#   severity: 1
# DeprecatedTag:
#   enabled: true
#   severity: 1
# EmptyBlockContent:
#   enabled: true
#   severity: 1
# ImgWidthAndHeight:
#   enabled: true
#   severity: 0
# JSONSyntaxError:
#   enabled: true
#   severity: 0
# LiquidFreeSettings:
#   enabled: true
#   severity: 1
# LiquidHTMLSyntaxError:
#   enabled: true
#   severity: 0
# MatchingTranslations:
#   enabled: true
#   severity: 0
# MissingAsset:
#   enabled: true
#   severity: 0
# MissingTemplate:
#   enabled: true
#   severity: 0
#   ignoreMissing: []
# PaginationSize:
#   enabled: true
#   severity: 1
#   minSize: 1
#   maxSize: 50
# ParserBlockingScript:
#   enabled: true
#   severity: 0
# RemoteAsset:
#   enabled: true
#   severity: 1
# RequiredLayoutThemeObject:
#   enabled: true
#   severity: 0
# SchemaPresetsBlockOrder:
#   enabled: true
#   severity: 1
# TranslationKeyExists:
#   enabled: true
#   severity: 0
# UnclosedHTMLElement:
#   enabled: true
#   severity: 1
# UndefinedObject:
#   enabled: true
#   severity: 1
# UniqueStaticBlockId:
#   enabled: true
#   severity: 0
# UnknownFilter:
#   enabled: true
#   severity: 0
# UnusedAssign:
#   enabled: true
#   severity: 1
# ValidBlockTarget:
#   enabled: true
#   severity: 0
# ValidContentForArguments:
#   enabled: true
#   severity: 0
# ValidHTMLTranslation:
#   enabled: true
#   severity: 1
# ValidJSON:
#   enabled: true
#   severity: 0
# ValidLocalBlocks:
#   enabled: true
#   severity: 0
# ValidSchema:
#   enabled: true
#   severity: 0
# ValidSchemaName:
#   enabled: true
#   severity: 0
# ValidStaticBlockType:
#   enabled: true
#   severity: 0
# VariableName:
#   enabled: true
#   severity: 1
#   format: snake_case
# 
```
