### ISSUE TITLE
/entrypoint.sh line 11: theme-check: command not found

### ISSUE THREAD

**Issue by ChalzZy** [Shopify/theme-check-action#53]
Started failing in the last 24 hours in our theme-check pipelines.

Here's the logs 

```terminal
Successfully installed ast-2.4.2
Successfully installed parser-3.3.6.0
Building native extensions. This could take a while...
ERROR:  Error installing theme-check:
	ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/3.0.0/gems/strscan-3.1.2/ext/strscan
/usr/bin/ruby -I /usr/lib/ruby/3.0.0 -r ./siteconf20250114-[7](...)-2bstrn.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

You might have to install separate package for the ruby development
environment, ruby-dev or ruby-devel for example.

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/3.0.0/gems/strscan-3.1.2 for inspection.
Results logged to /usr/lib/ruby/gems/3.0.0/extensions/x[8](...)6_64-linux-musl/3.0.0/strscan-3.1.2/gem_make.out
$ theme-check --version
/entrypoint.sh: line 11: theme-check: command not found
```

Workflow script

```
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Theme Check
        uses: shopify/theme-check-action@v1
        with:
          token: ${{ github.token }}
```
